run:
  timeout: 5m
  go: "1.24"
  modules-download-mode: readonly
  # Global Go version for all linters

# This is the version of golangci-lint configuration
# version: 2  # Commented out for v1 compatibility

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - godot
    - goheader
    - goprintffuncname
    - lll
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)
  lll:
    line-length: 140
  goheader:
    template-path: ""
    values:
      const:
        Author: "jsandas"
        Email: "jsandas@users.noreply.github.com"
        Year: "2024"
  goprintffuncname:
    prefix: "log"
  govet:
    check-shadowing: true
  staticcheck: {}
  ineffassign:
    check-blank: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  noctx:
    include: ""
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
  rowserrcheck:
    packages:
      - database/sql
  unconvert:
    fast: true
  unparam:
    check-exported: false
  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
        - goconst
        - gocritic
        - gosec
        - lll
        - goprintffuncname
        - gosec
        - govet
        - ineffassign
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - rowserrcheck
        - staticcheck
        - unconvert
        - unparam
        - whitespace
    - path: integration_test\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
        - goconst
        - gocritic
        - gosec
        - lll
        - goprintffuncname
        - gosec
        - govet
        - ineffassign
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - rowserrcheck
        - staticcheck
        - unconvert
        - unparam
        - whitespace
    - path: test_helpers\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
        - goconst
        - gocritic
        - gosec
        - lll
        - goprintffuncname
        - gosec
        - govet
        - ineffassign
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - rowserrcheck
        - staticcheck
        - unconvert
        - unparam
        - whitespace
  max-issues-per-linter: 0
  max-same-issues: 0
