run:
  timeout: 5m
  go: "1.24"
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - godot
    - goheader
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gomnd:
    checks: argument,case,condition,operation,return,assign
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)
  lll:
    line-length: 140
  goheader:
    template-path: ""
    values:
      const:
        Author: "jsandas"
        Email: "jsandas@users.noreply.github.com"
        Year: "2024"
  goprintffuncname:
    prefix: "log"
  gosimple:
    go-critic: true
  govet:
    check-shadowing: true
  ineffassign:
    check-blank: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  noctx:
    include: ""
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
  rowserrcheck:
    packages:
      - database/sql
  staticcheck:
    go: "1.24"
  structcheck:
    check-exported: false
  stylecheck:
    go: "1.24"
    initialisms:
      - ACL
      - API
      - ASCII
      - CPU
      - CSS
      - DNS
      - EOF
      - GUID
      - HTML
      - HTTP
      - HTTPS
      - ID
      - IP
      - JSON
      - QPS
      - RAM
      - RPC
      - SLA
      - SMTP
      - SQL
      - SSH
      - TCP
      - TLS
      - TTL
      - UDP
      - UI
      - GID
      - UID
      - UUID
      - URI
      - URL
      - UTF8
      - VM
      - XML
      - XMPP
      - XSRF
      - XSS
    checks: ["all", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-ST1023"]
  typecheck:
    go: "1.24"
  unconvert:
    fast: true
  unparam:
    check-exported: false
  unused:
    check-exported: false
  varcheck:
    check-exported: false
  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
        - goconst
        - gocritic
        - gosec
        - lll
        - gomnd
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - rowserrcheck
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace
    - path: integration_test\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
        - goconst
        - gocritic
        - gosec
        - lll
        - gomnd
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - rowserrcheck
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace
    - path: test_helpers\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
        - goconst
        - gocritic
        - gosec
        - lll
        - gomnd
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - rowserrcheck
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace
  max-issues-per-linter: 0
  max-same-issues: 0
