services:
  nginx:
    image: ghcr.io/jsandas/nginx_good
    volumes:
      - ./files/default.conf:/etc/nginx/conf.d/default.conf
      - ./files/nginx.config:/etc/nginx/nginx.conf
    ports:
      - "443:443"